blank_issues_enabled: false
contact_links:
  - name: 项目文档
    url: https://music.moekoe.cn/
    about: 查看项目文档以获取更多帮助信息
  - name: 开发与编译
    url: https://github.com/iAJue/MoeKoeMusic?tab=readme-ov-file#%EF%B8%8F-%E5%BC%80%E5%8F%91
    about: 了解项目如何进行开发和编译
  - name: 贡献指南
    url: https://github.com/iAJue/MoeKoeMusic/blob/main/CONTRIBUTING.md
    about: 了解如何为项目做出贡献
